# Generated by Django 3.0.14 on 2022-04-27 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='budy',
            new_name='body',
        ),
    ]
